name: README build

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v2
      - name: Setup NodeJs 13.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.16'
<<<<<<< HEAD
      # - name: Cache dependencies and build outputs to improve workflow execution time.
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
=======
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
>>>>>>> 932d2a2202595172fc0e5050653d04cd8955391c
      - name: Install dependencies
        run: npm install
      - name: Run build if present
        run: npm run build --if-present
      - name: Generate README file
        run: |- 
          node index.js
          cat README.md
      - name: Commit and Push new README.md to the repository
        run: |-
          git diff
          git config --global user.email "jacob.e.england@gmail.com"
          git config --global user.name "jeengland"
          git add -A
          git commit -m "Updated README.md" || exit 0
          git push
